### ISSUE TITLE
Homogenize .git directories in the project

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/starkiro#85]
### 📝 Description  
The current project structure includes multiple `.git` directories scattered across various scripts and contracts. For streamlined development and version control, the project should have only **one** centralized `.git` directory at the repository's root.  

The task involves:  
1. Identifying project directories containing separate `.git` directories.  
2. Removing these redundant `.git` directories while ensuring that the root `.git` directory remains intact.  

### 🔢 Steps  
1. Research the project structure to locate all `.git` directories outside the root.  
2. Delete the identified `.git` directories.  
3. Verify that the project functions correctly under a single global `.git` directory.  

### ✅ Acceptance Criteria  
- All redundant `.git` directories are removed.  
- The repository contains only the root `.git` directory.  
- Development workflows (e.g., commits, pushes, pulls) are unaffected and operate as expected.

**Comment by wheval** [comment]
Can I work on this when it is available?

**Comment by Benjtalkshow** [comment]
@danielcdz I can handle this and make PR in 5hrs from when this task will be assigned to me. Thanks

**Comment by Birdmannn** [comment]
@danielcdz I would love to handle this. 

I'll follow all steps listed above and ensure the development workflow remains unaffected


Eta 3 hours

**Comment by gadyrcdz** [comment]
Hey Sir, @danielcdz. Can I take care of this issue?
